language: ruby
rvm:
  - 2.2.3
  - 2.1.7

before_install:
    - gem update bundler
    - sudo apt-get update -qq
    - uname -a

install:
  # mecab
  - wget --no-check-certificate https://github.com/buruzaemon/natto/raw/master/etc/mecab-0.996.tar.gz && tar zxf mecab-0.996.tar.gz
  - pushd mecab-0.996 && ./configure --enable-utf8-only && make && sudo make install && popd
  - sudo ldconfig
  # mecab-ipadic
  - wget --no-check-certificate https://github.com/buruzaemon/natto/raw/master/etc/mecab-ipadic-2.7.0-20070801.tar.gz && tar zxf mecab-ipadic-2.7.0-20070801.tar.gz
  - pushd mecab-ipadic-2.7.0-20070801 && ./configure --with-charset=utf8 && make && sudo make install && popd
  - sudo ldconfig

script:
  - bundle exec rake spec
  - bundle exec rubocop
